# Universal token observations for G1-only five-point orientation tracking.

defaults:
  - ../terms/encoder_index@_here_
  - ../terms/command_multi_future_nonflat@_here_
  - ../terms/motion_anchor_ori_b_mf_nonflat@_here_
  - ../terms/motion_anchor_pose_w_mf@_here_
  - ../terms/endpoint_pose_root_local_mf@_here_

_target_: gear_sonic.envs.manager_env.mdp.observations.TokenizerCfg
enable_corruption: true
concatenate_terms: false

motion_anchor_ori_b_mf_nonflat:
  noise:
    _target_: isaaclab.utils.noise.AdditiveUniformNoiseCfg
    n_min: -0.05
    n_max: 0.05
